apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend-ingress
  labels:
    app: frontend
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - rcnuvas.co.in
    secretName: frontend-tls
  rules:
  - host: rcnuvas.co.in
    http:
      paths:
      - path: /.well-known/acme-challenge/
        pathType: Prefix
        backend:
          service:
            name: cm-acme-http-solver-q5mjc
            port:
              number: 8089
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend
            port:
              number: 80
